

# Define the services (containers) that make up your application
services:
  # Define the Flask application service
  flask_app:
    # Use the current directory as the build context for the Dockerfile
    build: ./src/
    # Map port 5000 on the host to port 5000 in the container
    ports:
      - "5000:5000"
    
    restart: always 
