services:
  # Define the Flask application service (Backend)
  flask_app:
    build:
      context: ./src/flask
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    restart: always
    # we set up a volume to persist the models directory, as it is out of the container's context
    volumes:
      - ./models:/app/models 
    environment:
      - MODEL_PATH=/app/models/ # The path where the models are stored inside the container
      
  # Define the Streamlit application service (Frontend)
  streamlit_app:
    build:
      context: ./src/streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - flask_app # The Flask container has to be up before the Streamlit app starts
    restart: always
    # The Flask backend is available within the Docker network using the service name 'flask_app'.
    environment:
      - FLASK_API_URL=http://flask_app:5000
